### Import Essential Libraries

In [1]:
# import libraries
import pandas as pd
import re
import numpy as np
import json
from pandas.io.json import json_normalize

### Load Dataframes

#### Song Names Dataframe

In [2]:
# create a dataframe from "names.csv" - holds names of the songs
song_names = pd.read_csv('names.csv')

In [3]:
# check the work
song_names

                             names
0             Sài Gòn Đau Lòng Quá
1                         LayLaLay
2                Xin Đừng Nhấc Máy
3              Có Lẽ Anh Chưa Từng
4                      Cho Mình Em
...                            ...
5670                Trong Tay Nhau
5671             Tren Ngon Doi Nho
5672      Nhung Tam Hon Hoang Lanh
5673            Buồn Làm Chi Em Ơi
5674  Liên khúc yêu nhau ghét nhau

[5675 rows x 1 columns]

#### Song Artists Dataframe

In [4]:
# create a dataframe from "artists.csv" - holds artists of the songs
song_artists = pd.read_csv('artists.csv')

In [5]:
# check the work
song_artists

            artists
0     Hứa Kim Tuyền
1        Jack - J97
2             B Ray
3            Only C
4              Binz
...             ...
5670       Tuan Anh
5671       Tuan Anh
5672       Tuan Anh
5673      Nhu Quynh
5674     Minh Tuyết

[5675 rows x 1 columns]

#### Song Popularity Dataframe

In [6]:
# create a dataframe from "lyrics.csv" - holds lyrics of the songs
song_popularity = pd.read_csv('popularity.csv')

In [7]:
# check the work
song_popularity

      popularity
0             64
1             60
2             58
3             48
4             56
...          ...
5670           4
5671           4
5672           2
5673          33
5674           5

[5675 rows x 1 columns]

#### Song Dates Dataframe

In [8]:
# create a dataframe from "genres.txt" - holds genres of the songs
song_dates = pd.read_csv('dates.csv')

In [9]:
# check the work
song_dates

           dates
0     2021-03-28
1     2021-04-12
2     2021-04-01
3     2021-04-01
4     2021-04-01
...          ...
5670        1998
5671        1998
5672        1998
5673  2020-08-22
5674  1992-01-01

[5675 rows x 1 columns]

#### Song Features Dataframe

In [10]:
# read "features.csv" - holds features of the songs
song_features = pd.read_csv('features.csv')
song_features = song_features.reset_index() 
song_features = song_features.drop(columns=['index', 'type', 'id', 'uri', 'track_href', 'analysis_url', 'time_signature'])

In [11]:
# check the work
song_features

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,0.418,0.382,3,-7.778,1,0.0319,0.7860,0.000001,0.3860,0.2610,163.878,308689
1,0.549,0.568,6,-8.159,0,0.1760,0.0859,0.000000,0.0863,0.3510,174.038,231724
2,0.873,0.755,7,-4.506,1,0.1400,0.2930,0.000000,0.0881,0.7730,94.017,187454
3,0.635,0.439,9,-10.434,0,0.0444,0.6090,0.000000,0.2000,0.6610,147.871,294535
4,0.603,0.412,0,-10.359,1,0.0579,0.8910,0.021200,0.1150,0.3710,99.886,206400
...,...,...,...,...,...,...,...,...,...,...,...,...
5670,0.504,0.116,11,-22.307,1,0.0326,0.7070,0.011100,0.1660,0.0464,115.098,385868
5671,0.471,0.129,4,-23.584,1,0.0306,0.5370,0.000032,0.0911,0.2140,108.536,265668
5672,0.432,0.281,11,-19.777,0,0.0385,0.4490,0.000000,0.4690,0.2200,151.556,343279
5673,0.342,0.407,11,-6.942,0,0.0265,0.6280,0.000150,0.2010,0.1160,99.077,358667
5674,0.709,0.901,7,-5.472,1,0.0400,0.1450,0.000121,0.1030,0.5610,131.990,682613

### Merge Dataframes

In [12]:
# merge above dataframes
df = pd.merge(song_names, song_artists, how='inner', left_index=True, right_index=True)
df = df.join(song_popularity)
df = df.join(song_dates)
df = df.join(song_features)

In [13]:
# remove rows 
df['names'] = df['names'].drop_duplicates()
df= df.dropna()
df = df.reset_index(drop=True)

In [14]:
# convert ms to s
df['duration_ms'] = df['duration_ms'] / 60000
df = df.rename(columns={'duration_ms': 'duration_min'})

In [15]:
# covert dates to datetime
df['dates'] = pd.to_datetime(df['dates'], errors='coerce')

# extract year
df['year'] = pd.to_datetime(df['dates']).dt.to_period('Y')

# drop dates columns
df = df.drop(columns='dates')

#### Data Codebook:
* names: Name of the song.
* artists: Artist(s) of the song.
* lyrics: Lyrics of the song.
* genres: Genre of the song.
* danceability: Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.
* energy: Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy.
* key: Key is the major or minor scale around which a piece of music revolves.
* loudness: The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track. Values typical range between -60 and 0 db. 
* mode: Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived.
* speechiness: Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value.
* acousticness: A measure from 0.0 to 1.0 of whether the track is acoustic.
* instrumentalness: Predicts whether a track contains no vocals. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content.
* liveness: Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live.
* valence: A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).
* tempo: The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.
* duration_ms: Duration of the song in millisecond.

In [16]:
# check the work
df

,names,artists,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_min,year
0,Sài Gòn Đau Lòng Quá,Hứa Kim Tuyền,64,0.418,0.382,3,-7.778,1,0.0319,0.7860,0.000001,0.3860,0.2610,163.878,5.144817,2021
1,LayLaLay,Jack - J97,60,0.549,0.568,6,-8.159,0,0.1760,0.0859,0.000000,0.0863,0.3510,174.038,3.862067,2021
2,Xin Đừng Nhấc Máy,B Ray,58,0.873,0.755,7,-4.506,1,0.1400,0.2930,0.000000,0.0881,0.7730,94.017,3.124233,2021
3,Có Lẽ Anh Chưa Từng,Only C,48,0.635,0.439,9,-10.434,0,0.0444,0.6090,0.000000,0.2000,0.6610,147.871,4.908917,2021
4,Cho Mình Em,Binz,56,0.603,0.412,0,-10.359,1,0.0579,0.8910,0.021200,0.1150,0.3710,99.886,3.440000,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3845,Thuong Nho Mot Nguoi,Tuan Anh,4,0.402,0.243,1,-18.882,0,0.0373,0.4550,0.000000,0.0834,0.2880,160.832,5.184850,1998
3846,Trong Tay Nhau,Tuan Anh,4,0.504,0.116,11,-22.307,1,0.0326,0.7070,0.011100,0.1660,0.0464,115.098,6.431133,1998
3847,Tren Ngon Doi Nho,Tuan Anh,4,0.471,0.129,4,-23.584,1,0.0306,0.5370,0.000032,0.0911,0.2140,108.536,4.427800,1998
3848,Nhung Tam Hon Hoang Lanh,Tuan Anh,2,0.432,0.281,11,-19.777,0,0.0385,0.4490,0.000000,0.4690,0.2200,151.556,5.721317,1998
3849,Liên khúc yêu nhau ghét nhau,Minh Tuyết,5,0.709,0.901,7,-5.472,1,0.0400,0.1450,0.000121,0.1030,0.5610,131.990,11.376883,1992

In [17]:
# write to csv file
df.to_csv('vpop.csv', index=False)